Implements Networking tables
CurtinFRC/2024-Crescendo pull request #99
Opened 2024-01-21 03:18 UTC by totallysomeoneyoudontknow

**What this PR does**

**What does it fix/add?**
Implements Networking Tables

**What does this depend on?**
_References pull requests or branches/forks that this pull request depends on_

2024-01-22 07:46 UTC, spacey-sooty requested changes
delete .vs folder

2024-01-23 07:05 UTC, goanna247 requested changes

2024-01-23 07:05 UTC, goanna247 commented on src/main/cpp/Shooter.cpp
> +  _rawVoltage = voltage;
set a default

2024-01-23 07:05 UTC, goanna247 commented on src/main/include/Robot.h
> +  behaviour::BehaviourScheduler* sched;
remove swerve stuff

2024-01-23 07:05 UTC, goanna247 commented on src/main/include/RobotMap.h
> +  struct SwerveBase {
remove swerve code

2024-01-23 07:05 UTC, goanna247 commented on src/main/include/Shooter.h
> +  units::volt_t _rawVoltage;
set a deafult

2024-01-23 12:34 UTC, merged